#ifndef DARKDASH_FONT_H
#define DARKDASH_FONT_H
/*---------------------------------------------------------------------------
    font.h -- Font atlas texture loader and glyph renderer (DarkDash).

    Reworked from SceneChat: now uses DarkDash's dd_ui (UI_Sx/UI_Sy) for
    virtual->screen scaling instead of the old ui.h. API unchanged.

    Uses the pre-baked font_atlas.h generated by gen_atlas.py.
    Three sizes: SMALL (14px), MEDIUM (18px), LARGE (24px).

    Call order:
        Font_Init(pDevice)    -- once after D3D8 device created
        Font_Shutdown()       -- on device release
        Font_DrawText(...)    -- during render
---------------------------------------------------------------------------*/
#include <xtl.h>
#include <d3d8.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FONT_SIZE_SMALL    0
#define FONT_SIZE_MEDIUM   1
#define FONT_SIZE_LARGE    2

    /* Colour packing helper -- ARGB */
#define FONT_RGBA(r,g,b,a) (((DWORD)(a)<<24)|((DWORD)(r)<<16)|((DWORD)(g)<<8)|(DWORD)(b))
#define FONT_WHITE          FONT_RGBA(255,255,255,255)
#define FONT_GREEN          FONT_RGBA(127,224,  0,255)   /* DarkDash accent #7FE000 */
#define FONT_GRAY           FONT_RGBA(170,170,170,255)
#define FONT_DARKGRAY       FONT_RGBA( 80, 80, 80,255)
#define FONT_BLACK          FONT_RGBA(  0,  0,  0,255)
#define FONT_RED            FONT_RGBA(220, 50, 50,255)

    int  Font_Init(IDirect3DDevice8* pDevice);
    void Font_Shutdown(void);

    /* Custom font support. Font_Init loads the baked "Default" failsafe. A .ddf
       from disk can be loaded live; on any failure the current font is untouched,
       so the dash never goes textless. Font_UseDefault reverts to the baked atlas. */
    int  Font_LoadDDF(IDirect3DDevice8* pDevice, const char* path);  /* 1 = loaded */
    int  Font_UseDefault(IDirect3DDevice8* pDevice);                 /* revert      */
    int  Font_IsCustom(void);                                        /* 1 = custom  */

    int  Font_MeasureText(const char* str, int size);
    int  Font_GlyphHeight(int size);
    /* recommended row pitch (glyph box + leading); use for list row spacing */
    int  Font_LineHeight(int size);

    void Font_DrawText(IDirect3DDevice8* pDevice,
        float x, float y, const char* str, int size, DWORD colour, int max_w);

    void Font_DrawTextCentered(IDirect3DDevice8* pDevice,
        float cx, float y, float width, const char* str, int size, DWORD colour);

    void Font_DrawTextRight(IDirect3DDevice8* pDevice,
        float x, float y, const char* str, int size, DWORD colour);

    /* Draw text ON the iso plane (tilts + scales with the chrome).
       MUST be called inside an Iso_Begin()/Iso_End() batch so the iso transform
       is active. Authored in virtual coords; conforms to the tilted panels. */
    void Font_DrawTextIso(IDirect3DDevice8* pDevice,
        float vx, float vy, const char* str, int size, DWORD colour);

    /* Iso text with a width budget (virtual px from vx): truncates cleanly so a
       long string can't overrun the panel. max_w <= 0 behaves like the unclipped
       version. */
    void Font_DrawTextIsoClip(IDirect3DDevice8* pDevice,
        float vx, float vy, const char* str, int size, DWORD colour, float max_w);

#ifdef __cplusplus
}
#endif
#endif /* DARKDASH_FONT_H */