#!/usr/bin/env python3
"""
theme_builder.py -- DarkDash theme builder / validator, GUI.

A DarkDash theme is just a folder:

    <name>/
        theme.ini
        assets/
            bar_header.png        (300x40)
            bar_footer.png        (624x32)
            frame_menu_v.png      (272x384)
            orb_hero.png          (272x234)
            platform_round.png    (pedestal art)
            overlay_selection_glow.png
            bg.png                (640x480, optional painted background)

This tool points at a theme folder, checks the asset slots, lets you set the
palette / glow / background options, and writes a correct theme.ini. It does
NOT pack anything -- the engine consumes folders directly, so you just copy the
folder to D:\\themes\\ on the Xbox.

Requires: pip install pillow  (only for size validation; ini writing is stdlib)
"""

import os
import sys

try:
    import tkinter as tk
    from tkinter import filedialog, messagebox, ttk, colorchooser
    HAVE_TK = True
except ImportError:
    HAVE_TK = False

try:
    from PIL import Image
    HAVE_PIL = True
except ImportError:
    HAVE_PIL = False

# slot name -> (recommended W, H, required?)
SLOTS = [
    ("bar_header",             300,  40, True),
    ("bar_footer",             624,  32, True),
    ("frame_menu_v",           272, 384, True),
    ("orb_hero",               272, 234, True),
    ("platform_round",         256, 120, True),
    ("overlay_selection_glow", 220,  40, False),
]
BG_SLOT = ("bg", 640, 480)   # optional painted background

DEFAULT_PALETTE = {
    "accent":     "7FE000",
    "accent_dim": "4C8A00",
    "glow":       "AEFF3C",
    "text":       "D8F8C0",
    "text_dim":   "7FA060",
    "bg":         "060A06",
}


def validate(theme_dir):
    """Return (lines, ok). lines = human-readable per-slot report."""
    assets = os.path.join(theme_dir, "assets")
    lines = []
    ok = True
    if not os.path.isdir(assets):
        return (["ERROR: no 'assets' sub-folder found"], False)

    for name, w, h, req in SLOTS:
        path = os.path.join(assets, name + ".png")
        if not os.path.isfile(path):
            mark = "MISSING (required)" if req else "missing (optional)"
            if req:
                ok = False
            lines.append("  %-26s %s" % (name + ".png", mark))
            continue
        if HAVE_PIL:
            try:
                im = Image.open(path)
                gw, gh = im.size
                note = "OK" if (gw, gh) == (w, h) else \
                       "size %dx%d (expected %dx%d)" % (gw, gh, w, h)
            except Exception as e:
                note = "unreadable: %s" % e
                ok = False
        else:
            note = "present (install Pillow to check size)"
        lines.append("  %-26s %s" % (name + ".png", note))

    # optional background
    bgp = os.path.join(assets, BG_SLOT[0] + ".png")
    if os.path.isfile(bgp):
        lines.append("  %-26s present (painted background)" % (BG_SLOT[0] + ".png"))
    return (lines, ok)


def write_ini(theme_dir, name, author, palette, glow_on, glow_color,
              glow_intensity, use_bg):
    p = os.path.join(theme_dir, "theme.ini")
    L = []
    L.append("; DarkDash theme -- generated by theme_builder.py")
    L.append("")
    L.append("[manifest]")
    L.append("schema_version  = 1")
    L.append("name            = %s" % name)
    L.append("author          = %s" % author)
    L.append("base_resolution = 640x480")
    L.append("asset_dir       = assets")
    L.append("")
    L.append("[palette]")
    for k in ("accent", "accent_dim", "glow", "text", "text_dim", "bg"):
        L.append("%-11s = %s" % (k, palette.get(k, DEFAULT_PALETTE[k])))
    L.append("")
    L.append("[glow]")
    L.append("enabled   = %d" % (1 if glow_on else 0))
    L.append("color     = %s" % glow_color)
    L.append("intensity = %d" % glow_intensity)
    L.append("")
    L.append("[background]")
    if use_bg:
        L.append("module = static")
        L.append("image  = assets/bg.png")
    else:
        L.append("module = none")
    L.append("")
    with open(p, "w") as f:
        f.write("\n".join(L) + "\n")
    return p


# ---------------------------------------------------------------------------
# GUI
# ---------------------------------------------------------------------------

class App:
    def __init__(self, root):
        self.root = root
        self.theme_dir = None
        self.palette = dict(DEFAULT_PALETTE)
        root.title("DarkDash Theme Builder")
        root.geometry("600x560")

        frm = ttk.Frame(root, padding=12)
        frm.pack(fill="both", expand=True)

        ttk.Label(frm, text="DarkDash Theme Builder",
                  font=("TkDefaultFont", 13, "bold")).pack(anchor="w")
        ttk.Label(frm, text="Point at a theme folder, set options, write theme.ini.",
                  foreground="#555").pack(anchor="w", pady=(0, 8))

        row = ttk.Frame(frm); row.pack(fill="x", pady=4)
        ttk.Button(row, text="Choose Theme Folder...",
                   command=self.choose).pack(side="left")
        self.lbl_dir = ttk.Label(row, text="(none)")
        self.lbl_dir.pack(side="left", padx=8)

        # meta
        meta = ttk.Frame(frm); meta.pack(fill="x", pady=4)
        ttk.Label(meta, text="Name").grid(row=0, column=0, sticky="w")
        self.e_name = ttk.Entry(meta, width=30); self.e_name.grid(row=0, column=1, padx=6)
        self.e_name.insert(0, "My Theme")
        ttk.Label(meta, text="Author").grid(row=1, column=0, sticky="w")
        self.e_auth = ttk.Entry(meta, width=30); self.e_auth.grid(row=1, column=1, padx=6)
        self.e_auth.insert(0, "")

        # palette swatches
        pal = ttk.LabelFrame(frm, text="Palette (RRGGBB)", padding=8)
        pal.pack(fill="x", pady=6)
        self.pal_entries = {}
        keys = ["accent", "accent_dim", "glow", "text", "text_dim", "bg"]
        for i, k in enumerate(keys):
            ttk.Label(pal, text=k).grid(row=i // 2, column=(i % 2) * 3, sticky="w", padx=2)
            e = ttk.Entry(pal, width=8); e.grid(row=i // 2, column=(i % 2) * 3 + 1, padx=2, pady=2)
            e.insert(0, self.palette[k])
            self.pal_entries[k] = e
            ttk.Button(pal, text="...", width=3,
                       command=lambda kk=k: self.pick_color(kk)).grid(
                       row=i // 2, column=(i % 2) * 3 + 2, padx=2)

        # glow
        gl = ttk.LabelFrame(frm, text="Glow", padding=8)
        gl.pack(fill="x", pady=6)
        self.glow_on = tk.IntVar(value=1)
        ttk.Checkbutton(gl, text="Enabled", variable=self.glow_on).grid(row=0, column=0, sticky="w")
        ttk.Label(gl, text="Color").grid(row=0, column=1, padx=4)
        self.e_glow = ttk.Entry(gl, width=8); self.e_glow.grid(row=0, column=2)
        self.e_glow.insert(0, "AEFF3C")
        ttk.Button(gl, text="...", width=3, command=self.pick_glow).grid(row=0, column=3, padx=2)
        ttk.Label(gl, text="Intensity").grid(row=0, column=4, padx=4)
        self.glow_i = tk.IntVar(value=100)
        ttk.Scale(gl, from_=0, to=100, variable=self.glow_i, length=120).grid(row=0, column=5)

        # background
        bg = ttk.Frame(frm); bg.pack(fill="x", pady=4)
        self.use_bg = tk.IntVar(value=0)
        ttk.Checkbutton(bg, text="Use painted background (assets/bg.png)",
                        variable=self.use_bg).pack(side="left")

        # validation report
        self.txt = tk.Text(frm, height=10, width=70, bg="#0c120c", fg="#bdd",
                           highlightthickness=1, highlightbackground="#333")
        self.txt.pack(fill="both", expand=True, pady=6)

        actions = ttk.Frame(frm); actions.pack(fill="x")
        ttk.Button(actions, text="Validate", command=self.do_validate).pack(side="left")
        ttk.Button(actions, text="Write theme.ini", command=self.do_write).pack(side="left", padx=6)
        self.lbl_status = ttk.Label(frm, text="", foreground="#080")
        self.lbl_status.pack(anchor="w")

    def choose(self):
        d = filedialog.askdirectory(title="Choose a theme folder")
        if not d:
            return
        self.theme_dir = d
        self.lbl_dir.config(text=os.path.basename(d.rstrip("/\\")))
        self.do_validate()

    def pick_color(self, key):
        c = colorchooser.askcolor()[1]
        if c:
            self.pal_entries[key].delete(0, "end")
            self.pal_entries[key].insert(0, c.lstrip("#").upper())

    def pick_glow(self):
        c = colorchooser.askcolor()[1]
        if c:
            self.e_glow.delete(0, "end")
            self.e_glow.insert(0, c.lstrip("#").upper())

    def do_validate(self):
        self.txt.delete("1.0", "end")
        if not self.theme_dir:
            self.txt.insert("end", "Choose a theme folder first.\n")
            return
        lines, ok = validate(self.theme_dir)
        self.txt.insert("end", "Asset slots:\n")
        self.txt.insert("end", "\n".join(lines))
        self.txt.insert("end", "\n\n" + ("All required slots present.\n" if ok
                                         else "Missing required slots -- theme may render with gaps.\n"))

    def do_write(self):
        if not self.theme_dir:
            messagebox.showwarning("No folder", "Choose a theme folder first.")
            return
        pal = {k: self.pal_entries[k].get().strip().lstrip("#").upper()
               for k in self.pal_entries}
        try:
            p = write_ini(self.theme_dir, self.e_name.get(), self.e_auth.get(),
                          pal, self.glow_on.get(), self.e_glow.get().strip().lstrip("#").upper(),
                          int(self.glow_i.get()), self.use_bg.get())
            self.lbl_status.config(text="Wrote " + p, foreground="#080")
        except Exception as e:
            messagebox.showerror("Write failed", str(e))


def main():
    # headless: theme_builder.py <theme_dir>   (validate only)
    if len(sys.argv) == 2:
        lines, ok = validate(sys.argv[1])
        print("\n".join(lines))
        print("OK" if ok else "MISSING REQUIRED SLOTS")
        return
    if not HAVE_TK:
        print("Usage (headless validate): theme_builder.py <theme_dir>")
        return
    root = tk.Tk()
    App(root)
    root.mainloop()


if __name__ == "__main__":
    main()